### ISSUE TITLE
Log Out Auth0 Users

### ISSUE THREAD

**Issue by rob-h-m** [SmartColumbusOS/discovery#16]
@rob-h-m commented on [Mon Sep 09 2019](https://github.com/smartcitiesdata/discovery_ui/issues/206)

#### User Story:

As Connor
I would like to be able to have a personalized experience in the discovery apps
So that I can favorite datasets, create charts, and return to them in the future

#### Acceptance Criteria:
- [ ] Users who logged in with Auth0 can log out
- [ ] After logging out, they can log back in

#### Business Value:
1.) Lays the foundation for improved user experience in the OS through personalization
2.) Continued separation between public and restricted datasets
3.) Risk reduction by implementing through external account management services such as Google

#### Amigos:
@carriebrinkley , @JarredOlson 

---

@abrock-accenture commented on [Tue Sep 24 2019](https://github.com/smartcitiesdata/discovery_ui/issues/206#issuecomment-534693991)

@carriebrinkley @rob-h-m Logout functionality from the UI is already complete.  The only piece that *may* be missing is the possibility of revoking the user's token so it can no longer be used.  This definitely more work than the 1 point on this card, and we may want to have a conversation about whether this is something we want/need.

**Comment by ManApart** [comment]
Closing as this is already feature parity with LDAP
